# Generated by Django 3.0.4 on 2020-03-15 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('text', models.CharField(max_length=255)),
                ('process_time', models.DateTimeField()),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.SnippetResults')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.IntegerField(null=True)),
                ('risk_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='core.Snippet')),
            ],
        ),
    ]
