# Generated by Django 3.0.4 on 2020-03-16 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='snippet',
            name='risk_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='process_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='results',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SnippetResults'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
