# Generated by Django 3.0.4 on 2020-03-16 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200316_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='results',
        ),
        migrations.AddField(
            model_name='snippetresults',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippetresults',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.Snippet'),
        ),
        migrations.AlterField(
            model_name='snippetresults',
            name='results',
            field=models.BinaryField(null=True),
        ),
    ]
