# Generated by Django 3.0.4 on 2020-04-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200316_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptableUsePolicyRule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('full_rule', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='snippetresults',
            old_name='results',
            new_name='binary_results',
        ),
        migrations.AddField(
            model_name='snippet',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippetresults',
            name='assessed_risk_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='snippetresults',
            name='is_against_aup',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippetresults',
            name='report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippetresults',
            name='snippet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_set', to='core.Snippet'),
        ),
    ]
