# Generated by Django 3.0.4 on 2020-04-12 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200412_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetresults',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
