# Generated by Django 3.0.4 on 2020-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200412_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='domicile',
            field=models.CharField(default='GB', max_length=2),
            preserve_default=False,
        ),
    ]
