# Generated by Django 3.0.4 on 2020-04-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_snippet_domicile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptableusepolicyrule',
            name='keywords',
        ),
    ]
