# Generated by Django 3.0.4 on 2020-04-13 07:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_acceptableusepolicyrule_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptableusepolicyrule',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
