# Generated by Django 3.0.4 on 2020-04-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_acceptableusepolicyrule_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptableusepolicyrule',
            name='keywords',
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('risk_weight', models.IntegerField(null=True)),
                ('aup_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywords', to='core.AcceptableUsePolicyRule')),
            ],
        ),
    ]
