# Generated by Django 3.0.4 on 2020-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200413_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='aup_rule',
        ),
        migrations.AddField(
            model_name='keyword',
            name='aup_rule',
            field=models.ManyToManyField(related_name='keywords', to='core.AcceptableUsePolicyRule'),
        ),
    ]
