# Generated by Django 3.0.4 on 2020-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200413_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('risk_weight', models.IntegerField(null=True)),
                ('aup_rule', models.ManyToManyField(related_name='phrases', to='core.AcceptableUsePolicyRule')),
            ],
        ),
    ]
