# Generated by Django 3.0.4 on 2020-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200417_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='language',
            field=models.CharField(default='EN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phrase',
            name='language',
            field=models.CharField(default='EN', max_length=2),
            preserve_default=False,
        ),
    ]
