# Generated by Django 3.0.4 on 2020-04-20 17:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200417_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='pattern',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
